name: Sync src to org repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Clone org repo and copy src
        run: |
          git clone https://mvajhi:$ORG_TOKEN@github.com/PLC-UT/phase-4-null.git org-repo
          rm -rf org-repo/src/
          cp -r ca2/src org-repo/
          mkdir org-repo/src/parsers
          cp -r ca2/gen/main/grammar/* org-repo/src/parsers/
          ls ./ca2/src -R
          cd org-repo
          ls ./src -R
          git config user.name "GitHub Action"
          git config user.email "mvajhimv@gmail.com"
          git status
          git add -A
          git status
          git commit -m "Auto-sync src folder from personal repo"
          git push https://$ORG_TOKEN@github.com/PLC-UT/phase-4-null.git main
        env:
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}

